### ISSUE TITLE
Edit Profile doesn't work when I use my own Tenant information.

### ISSUE THREAD

**Issue by armyofthe12monkeys** [Azure-Samples/ms-identity-javascript-react-tutorial#291]
# Issue

Hello,
I'm having an issue where the 'Edit Profile' functionality just redirects back to my localhost:3000 app... 
The Tasklist feature seems to work, but the Edit Profile feature does not.
I changed the tenant/client-id information to my own. Also to keep it simple on my permissions side, I just have 1 scope permission called 'Scope.All' which I also changed anywhere the ToDoList.Read/ToDoList.ReadWrite shows up. 
I did this so I could apply it to all my API's then change it to get more detailed permissions later on.
Note: i also have a separate code-base where i left the ToDoList.Read/ToDoList.ReadWrite scopes in (which I also have in Azure), and still have the same issue.
If it is useful to debug the issue, the url it tries to create in the code to redirect to is in one of the sections below.

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ x ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ x ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

When i debug via DevTools, AzureB2C creates this **navigateUrl** url via this code:
```
           // Create acquire token url.
            const navigateUrl = await authClient.getAuthCodeUrl({
                ...validRequest,
                nativeBroker: NativeMessageHandler.isNativeAvailable(this.config, this.logger, this.nativeMessageHandler, request.authenticationScheme)
            });
```
that I assume it tries to redirect to in order to edit my profile:

https://patientportalb2cdev.b2clogin.com/patientportalb2cdev.onmicrosoft.com/b2c_1_edit_profile/oauth2/v2.0/authorize?client_id=c1d2e539-4d27-45b9-b10d-163e44036e41&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&client-request-id=b20aa729-48a2-4c97-a8e7-ea99fb0d1a6b&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.31.0&client_info=1&code_challenge=G2ZxwFmp-1Octau0LlIV9E-0Z_-LhIMAF1ZJwZyqrWY&code_challenge_method=S256&login_hint=acurian.testing%40gmail.com&X-AnchorMailbox=Oid%3Ae8a52a20-57ba-4188-855f-316c09a2af99-b2c_1_susi%4089fe1c88-6121-4253-931c-18b20a0e7807&nonce=00600125-d707-479b-bbe8-1190d74a77ca&state=eyJpZCI6IjFiNmYwZDBlLTUwZmMtNDljMy1hNjViLTNjYWE2OTYxMjNjZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D

but it seems like the app immediately redirects back to localhost:3000. 
and it also removes my email info from the top-right button:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/60300754/28f10f87-7659-4bbe-9c0d-3c2e2e9f7d41).

If I manually goto the above url in my browser, it redirects along with this state information:

http://localhost:3000/#state=eyJpZCI6IjFiNmYwZDBlLTUwZmMtNDljMy1hNjViLTNjYWE2OTYxMjNjZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3d&client_info=eyJ1aWQiOiJlOGE1MmEyMC01N2JhLTQxODgtODU1Zi0zMTZjMDlhMmFmOTktYjJjXzFfZWRpdF9wcm9maWxlIiwidXRpZCI6Ijg5ZmUxYzg4LTYxMjEtNDI1My05MzFjLTE4YjIwYTBlNzgwNyJ9&code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..IU7o_pErd-BfHQLK.2GS7gKlD5bV-qw_8wi8xwOAv_2fnSslI3FRO82j403Kce2ywo2R0Duu5GDsqnIIFlH2ZAduOpjRuQbYuW5wVId9EZHx_qAcJaC3TVvQYiv3V6oKCOeVyhNiCpRiZGXN9QIKb_bP56nvS5VVS-y-vYNWoUnn1mqw727eFXh-i_gE_a1QEm1huKYyxUA6n27joKt7vA_KlSdC7x1xoSiPJa2mwPfCnec3wk7RuQYhQy46cSlpBTB4i9CztVIVaGwBIJRP74xVszLcf8GezLaNNIfAPSrYP1FBgAavSHGevs6DX0scru1e5j6oKaSUuWksoWZ0dLCO3QPm2iHA2hf2sJx8xZE-kikSAoxBcuMjaPnJBsUpY_u_QMsW7_gB0UI9VegNsQvpch43FSNLyUQIGP_-258KhITuOXZSwIFUHvO9MrUNg0pFQ2df-EhFEwq54e2J0HabT8cVtpUs3rKbsO3R--hOnCrIZG8i8KB_TYz8P27wu72UyIR3ABMC6-UdTf6uSQ5m-yWlwDjAUcAe82cPT6jX8ireqgHC5lREmn2aSl1hPQ0rGdZxj20j9PVOBQE1z71Js7V4_HCmBK-Ux8Stc5ICuk7-1yEY5IpHVo7am8rP-fM1hq04rKghyXcv51h2bsM8SyqE2mHRl8gDA8xwFglpsoFTaH66R1i_gRA.BnmpVo_-mslZfUnAJZzEkw

### Any log messages given by the failure

Nothing really stands out on the console.

### Expected/desired behavior

Should show the edit profile page, similar to the original example.

### Library version

"@azure/msal-browser": "~2.31.0",
"@azure/msal-react": "~1.4.10",

### Browser and version

Chrome

### Mention any other details that might be useful

Note: my user flows are called: B2C_1_susi and B2C_1_edit_profile and hence i changed them in the authConfig.js
My client ID of my SPA project is:
  c1d2e539-4d27-45b9-b10d-163e44036e41
My client ID of my API project is:
  d9552fa1-8ca5-4fdd-82c1-a54d8b956cdc
The Scope.All scope in the API project is: 
  https://patientportalb2cdev.onmicrosoft.com/d9552fa1-8ca5-4fdd-82c1-a54d8b956cdc/Scope.All
If want to just use the original read/write scopes to keep things simple (so don't have to modify the **3-Authorization-II\2-call-api-b2c** code, minus the authConfig.js files), those are at:
https://patientportalb2cdev.onmicrosoft.com/d9552fa1-8ca5-4fdd-82c1-a54d8b956cdc/ToDoList.Read
https://patientportalb2cdev.onmicrosoft.com/d9552fa1-8ca5-4fdd-82c1-a54d8b956cdc/ToDoList.ReadWrite
The b2cPolicies.names are (which also get append onto the b2cPolicies.authorities urls like: 
authority: 'https://patientportalb2cdev.b2clogin.com/patientportalb2cdev.onmicrosoft.com/B2C_1_susi'): 
		signUpSignIn: 'B2C_1_susi',
		forgotPassword: 'B2C_1_passwordreset',
		editProfile: 'B2C_1_edit_profile',

Note: I may delete some of these above details later after getting help here.

**Comment by derisen** [comment]
@armyofthe12monkeys apologies for the late response, this one seem to fell through cracks. Your issue is most likely a problem with how you set up the edit profile user flow. As a first step, are you able to launch and test the edit profile user-flow via Azure portal? (see https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow#test-the-user-flow-1).

Regarding the issue where your email is removed on the navbar ("unkown"), can you confirm you have followed the steps in the warning here: https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/2-call-api-b2c/README.md#create-user-flows-and-custom-policies

Do you have (or can you put together) a repo to reproduce the issue with? That would help me debug it.

**Comment by armyofda12mnkeys** [comment]
Hey @derisen !
> As a first step, are you able to launch and test the edit profile user-flow via Azure portal? 

I did test my b2c_1_edit_profile via 'Run user flow', and got a valid JSON response back after signing in on the jwt.ms page.

> Can you confirm you have followed the steps in the warning here? https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/2-call-api-b2c/README.md#create-user-flows-and-custom-policies

Yes I think so. 
Note: the instructions there i don't think mention which User Flow to select once you go into 'User Flows', in this part:
**"Then, navigate to the User flows blade. Select the User Attributes tab and make sure Email Address is checked. Then select the Application Claims tab and make sure Email Addresses is checked."**

But I checked the **susi** (which has Email Address in the User Attribute section and Email Addresses in the Application Claims section)
and **signin** (has just the Application Claims section and saw Email Addresses in there).


> Also, do you have (or can you put together) a repo to reproduce the issue with? That would help me debug it.

Yes, I just added you to my private repository on here.
Let me know if anything sticks out.

Thanks again for helping out,
Arian

**Comment by armyofda12mnkeys** [comment]
Hey,
So by default the edit_profile flow doesn't have Email at all in User Attributes section of that flow:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/410112/30d9d2d8-b6c1-4ad1-89c4-44569e323bcc)

and the Application Claims section of edit_profile had Email Addresses unchecked (maybe by default).
I'm going to check that one now and retest and report back:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/410112/84acb275-9eb1-4147-8531-c2230812a547)

**Comment by armyofda12mnkeys** [comment]
Hey @derisen ,
i think the issue where the email address disappears from top-right area is good after above.
But the main issue still occurs where it doesn't open up the Edit Profile popup.

Not sure if its related to the allowed Redirect URIs, but i added a few urls in there like these localhost urls (and the jwt.js site as well for 'Run User Flow' testing).
Note: this is redirect settings for the FrontEnd SPA app in Azure, not the BackEnd API app:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/410112/927d6ea4-53a7-4572-8f1f-5e9d71c4be73)

Think thats correct as its mentioned in the docs:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/410112/2c2d6bd6-3fd4-40fe-a1dd-93ca9e95634f)

Testing via Run User Flow gives me this result in the jwt.ws:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/410112/21b7e9c3-d4de-4001-b96a-1ad2d82f5cb3)

Anyway, let me know what else to try.
Let me know if you can replicate with a user you signed up yourself... My account is created using the regular Email/Password type of Signup.
If you cannot replicate, then i can give my user/pass maybe privately to you via email.

Thanks!,
Arian

**Comment by derisen** [comment]
Great! Glad that resolves the "unknown" username issue. I'll try to sign-up with my own account and give it a try.

**Comment by derisen** [comment]
@armyofda12mnkeys I'm able to reproduce the issue, but couldn't identified the root cause yet. Can you help me with a couple of things:

- When you were testing b2c_1_edit_profile via the 'Run user flow' on Azure portal, can you tell me what is the URL/endpoint it navigates you to? Can you share that with me?

- Can you confirm that in your app registration, none of the implicit flow boxes are checked (this is on the "Authentication" page). Feel free to share your app manifest as well.

**Comment by armyofda12mnkeys** [comment]
> When you were testing b2c_1_edit_profile via the 'Run user flow' on Azure portal, can you tell me what is the URL/endpoint it navigates you to? Can you share that with me?

So the signin popup it goes to is:
https://patientportalb2cdev.b2clogin.com/patientportalb2cdev.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_edit_profile&client_id=c1d2e539-4d27-45b9-b10d-163e44036e41&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login

and after signin, it redirects to here (since i choose https://jwt.ms in the Run User Flow's Reply URL dropdown)
https://jwt.ms/#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJ2ZXIiOiIxLjAiLCJpc3MiOiJodHRwczovL3BhdGllbnRwb3J0YWxiMmNkZXYuYjJjbG9naW4uY29tLzg5ZmUxYzg4LTYxMjEtNDI1My05MzFjLTE4YjIwYTBlNzgwNy92Mi4wLyIsInN1YiI6ImU4YTUyYTIwLTU3YmEtNDE4OC04NTVmLTMxNmMwOWEyYWY5OSIsImF1ZCI6ImMxZDJlNTM5LTRkMjctNDViOS1iMTBkLTE2M2U0NDAzNmU0MSIsImV4cCI6MTY4NzMzMTU0OSwibm9uY2UiOiJkZWZhdWx0Tm9uY2UiLCJpYXQiOjE2ODczMjc5NDksImF1dGhfdGltZSI6MTY4NzMyNzk0OSwiZW1haWxzIjpbImFjdXJpYW4udGVzdGluZ0BnbWFpbC5jb20iXSwidGZwIjoiQjJDXzFfZWRpdF9wcm9maWxlIiwibmJmIjoxNjg3MzI3OTQ5fQ.lKJ5FH57ugZGkax5dbHjAX4chKTkA2BvgKgUxlt5yaEYcMP8FBkX3-AV2pqitcTiKY5hhzEdw9wLl8ZMwHYnq_K6T7hQGlnCrVCFzX0VENmwKzSiA14JT2OBlaQ21NfJqIjuIU1q62t5uv1uJgaTL56UsjN6M-inNfwJAosGnNLHvjMYo6mpISKkafKfvAag0fT0blhhDRXfFj_nx-jY5qJN9MJZLTbq60hoB7S80FAXUO1tpojqL16muNfoVzefyJ27TaR0GE1-DiN2pUEzrMQh72h6h4F4V34tcJqAGMInOBEbat6t7jo1VlVl4aDOiCfmP3Q6Un13FdcjIeHD9A


> Can you confirm that in your app registration, none of the implicit flow boxes are checked (this is on the "Authentication" page). Feel free to share your app manifest as well.

Hmmm the 2 checkboxes are checked:
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/410112/67f6d5eb-8392-4c0c-9246-72fc3a303d11)

I don't remember checking them but looks like I prob did since that is not the default setting,
Hmmm let me unset for now.
Just tested though, and didn't seem to make a difference.

Btw which file is the App Manifest? something not in the git repo i assume, within the Azure portal?

**Comment by armyofda12mnkeys** [comment]
Found it, Here is the app manifest:

[app-manifest-from-azure-portal.txt](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/files/11814228/app-manifest-from-azure-portal.txt)

**Comment by derisen** [comment]
@armyofda12mnkeys I'm unable to crack this :/ There seems nothing wrong with the request to B2C, and no visible errors either. 

The expectation is:

1. app navigates the user's browser to `https://patientportalb2cdev.b2clogin.com/patientportalb2cdev.onmicrosoft.com/b2c_1_edit_profile/oauth2/v2.0/authorize` endpoint.
2. A UI will prompt the user
3. user interacts with the UI (next or cancel) 
4. B2C will redirect back to your redirect uri with authZ code 

Here, step 2 is just not happening...

Let's try a few more things:

- Uncheck the "Allow public client flows" on the Authentication page on app registration portal
- Make sure both `localhost:3000` and `localhost:3000/redirect` are registered as SPA redirect URIs
- Make sure you are using the latest version of B2C user-flows: https://learn.microsoft.com/en-us/azure/active-directory-b2c/user-flow-versions

If the issue persists after, you might want to open a [support ticket](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket#open-a-support-ticket) with B2C to take a look at your user-flow

**Comment by armyofda12mnkeys** [comment]
so if i uncheck the "Allow public client flows" my real application stops working and gives an error trying to signup:
ServerError: unauthorized_client: AADB2C90058: The provided application is not configured to allow public clients.
Correlation ID: f6f66358-8b63-4a98-97a7-98fb4c51eac6
Timestamp: 2023-06-22 00:37:18Z

When i say my 'real application', i mean not this more simpler test github app i shared thats an exact copy of the repo, minus the authConfig.js, but the actual SPA app we have deployed to real environments. So I had to re-enable it other my QA Team will complain the login isn't working tomorrow in our NonProd envs.

So i switched it back to Enabled. I assume this setting is actually needed?

Yes, both those urls are in my SPA Redirect URls.
